import React from "react";
import PropTypes from "prop-types";
import { Tabs, Tab, Typography, Box, useTheme, useMediaQuery } from "@mui/material";
import FadeInSection from "./FadeInSection";

function TabPanel({ children, value, index, isMobile, ...other }) { return <div role="tabpanel" hidden={value !== index} id={`${isMobile ? "full-width" : "vertical"}-tabpanel-${index}`} {...other}>{value === index && <Box sx={{ p: { xs: 2, sm: 3 } }}><Typography component="div">{children}</Typography></Box>}</div>; }
TabPanel.propTypes = { children: PropTypes.node, index: PropTypes.number.isRequired, value: PropTypes.number.isRequired, isMobile: PropTypes.bool };
const experienceItems = {
  "Novalith Marketing": { jobTitle: "Project Manager @", duration: "APR 2025 — PRESENT", desc: ["Develop and manage plans, schedules, and resources for 25+ cross-functional projects, achieving 95% on-time delivery.", "Coordinate teams and resolve delivery issues to cut campaign turnaround time by 30%.", "Analyse Meta, Google, and TikTok performance to find opportunities that lifted conversion rates by 25–40%."] },
  ReconXi: { jobTitle: "Project Manager @", duration: "JAN 2025 — APR 2026", desc: ["Managed delivery of an AI-powered financial-reconciliation product across web and mobile within three-week release cycles.", "Owned project documentation, timelines, sprint plans, and resourcing trackers, reducing project misalignment by 20%.", "Prepared demos and stakeholder presentations that contributed to a 25% increase in client acquisition."] },
  FitsCheck: { jobTitle: "Project Manager @", duration: "APR 2024 — JAN 2025", desc: ["Developed the roadmap and implementation plan that took MVP features to launch readiness within eight weeks.", "Managed schedules, budgets, and allocation for a six-person design, development, and QA team, improving sprint consistency by 40%.", "Tested with 30 early adopters and used findings to reduce onboarding drop-off by 10%."] },
  "HNG Tech": { jobTitle: "Product Management Intern @", duration: "JAN 2024 — APR 2024", desc: ["Conducted market and competitor research across six products to support MVP scope and planning.", "Created PRDs, user stories, and requirements that reduced revision cycles by 20%.", "Supported usability tests and improvements that increased usability scores by 15%."] },
};
const JobList = () => { const [value, setValue] = React.useState(0); const isMobile = useMediaQuery(useTheme().breakpoints.down("md")); const names = Object.keys(experienceItems); return <Box sx={{ flexGrow: 1, bgcolor: "transparent", display: "flex", flexDirection: isMobile ? "column" : "row", minHeight: 300 }}><Tabs orientation={isMobile ? "horizontal" : "vertical"} variant="scrollable" scrollButtons="auto" value={value} onChange={(_, next) => setValue(next)} sx={{ borderRight: isMobile ? 0 : 1, borderBottom: isMobile ? 1 : 0, borderColor: "var(--lightest-navy)", "& .MuiTabs-indicator": { backgroundColor: "var(--green-bright)" } }}>{names.map((name) => <Tab key={name} label={name} sx={{ color: "var(--slate)", fontFamily: "NTR", fontSize: "14px", textTransform: "none", alignItems: isMobile ? "center" : "flex-start", minWidth: isMobile ? 128 : "auto", "&.Mui-selected": { color: "var(--green-bright)" }, "&:hover": { color: "var(--green-bright)", backgroundColor: "var(--green-tint)" } }} />)}</Tabs><Box sx={{ flexGrow: 1 }}>{names.map((name, index) => { const item = experienceItems[name]; return <TabPanel key={name} value={value} index={index} isMobile={isMobile}><span className="joblist-job-title">{item.jobTitle} </span><span className="joblist-job-company">{name}</span><div className="joblist-duration">{item.duration}</div><ul className="job-description">{item.desc.map((description, i) => <FadeInSection key={description} delay={`${(i + 1) * 100}ms`}><li>{description}</li></FadeInSection>)}</ul></TabPanel>; })}</Box></Box>; };
export default JobList;
