import React from "react";
import "../styles/Projects.css";
import FolderOpenRoundedIcon from "@mui/icons-material/FolderOpenRounded";
import FadeInSection from "./FadeInSection";
import { Carousel } from "react-bootstrap";
import ExternalLinks from "./ExternalLinks";

const featured = [
  { title: "Sonora", desc: "Spotify music recommendation platform built around audio-feature data and listening patterns.", techStack: "PYTHON, RECOMMENDATION SYSTEMS", github: "https://github.com/AdegokeV/Spotify_Music_Recommendation", live: "https://sonora-music-recommendation.vercel.app/", image: "/assets/sonora-preview.png" },
  { title: "Tuberculosis Prediction App", desc: "Machine-learning application for TB risk prediction, deployed with Streamlit.", techStack: "PYTHON, ML, STREAMLIT", github: "https://github.com/AdegokeV/Tuberculosis_Prediction_App", live: "https://tuberculosis-prediction-app-ten.vercel.app/", image: "/assets/tuberculosis-preview.png" },
  { title: "Flower Classifier", desc: "Image-classification model for flower species identification, deployed with Streamlit.", techStack: "COMPUTER VISION, STREAMLIT", github: "https://github.com/AdegokeV/flower-classifier-streamlit", live: "https://flower-classifier-app-extglphvusu4v9ypievqcq.streamlit.app/", image: "/assets/flower-preview.png" },
  { title: "Loan Default Prediction", desc: "Credit-risk prediction tool comparing ANN, Logistic Regression, KNN, and Random Forest models.", techStack: "PYTHON, CLASSIFICATION, STREAMLIT", github: "https://github.com/AdegokeV/loan_default_prediction_app", live: "https://adegokev-loan-default-prediction-app-app-gg1ovz.streamlit.app/", image: "/assets/loan-default-preview.png" },
];
const projects = [...featured, { title: "PeakPacer SQL", desc: "SQL-based data project exploring structured data through practical queries.", techStack: "SQL, DATA ANALYSIS", github: "https://github.com/AdegokeV/PeakPacer" }];

const Projects = () => <section id="projects"><div className="section-header"><span className="section-title">/ data projects</span><a href="https://github.com/AdegokeV" className="explore-link" target="_blank" rel="noreferrer">View all projects</a></div><div className="spotlight-projects-desktop"><Carousel interval={null}>{featured.map((project) => <Carousel.Item key={project.title}><a className="featured-project-link" href={project.live} target="_blank" rel="noreferrer" aria-label={`Open ${project.title} live site`}><img className="d-block w-100" src={project.image} alt={`${project.title} application`} /></a><Carousel.Caption><h3>{project.title}</h3><div>{project.desc}<div className="techStack">{project.techStack}</div><ExternalLinks githubLink={project.github} liveLink={project.live} /></div></Carousel.Caption></Carousel.Item>)}</Carousel></div><div className="spotlight-projects-mobile">{featured.map((project, index) => <FadeInSection key={project.title} delay={`${(index + 1) * 90}ms`}><article className="projects-card"><a className="project-preview" href={project.live} target="_blank" rel="noreferrer"><img src={project.image} alt={`${project.title} application`} /><span className="preview-overlay"><strong>{project.title}</strong><em>Visit live site ↗</em></span></a><div className="card-title">{project.title}</div><div className="card-desc">{project.desc}</div><div className="card-tech">{project.techStack}</div><ExternalLinks githubLink={project.github} liveLink={project.live} /></article></FadeInSection>)}</div><div className="project-container"><ul className="projects-grid">{projects.map((project, index) => <FadeInSection key={project.title} delay={`${(index + 1) * 70}ms`}><li className="projects-card"><div className="card-header"><div className="folder-icon"><FolderOpenRoundedIcon sx={{ fontSize: 35 }} /></div><ExternalLinks githubLink={project.github} liveLink={project.live} /></div><div className="card-title">{project.title}</div><div className="card-desc">{project.desc}</div><div className="card-tech">{project.techStack}</div></li></FadeInSection>)}</ul></div></section>;
export default Projects;
